### ISSUE TITLE
Electron用MAC自己签名我记得是免费的

### ISSUE THREAD

**Issue by hugetiny** [sunzongzheng/electron-updater#1]
我以前做过Electron的项目
https://github.com/hugetiny/negibox
自己签名是免费的，国外的用户也能通过Electron-updater自动更新
我这里就算架了梯子，github release（亚马逊的S3）也很慢，所以国内没有成功更新过，只能花钱买其他更新服务器
你这里实际情况怎么样？

**Comment by hugetiny** [comment]
Electron builder 关于如何自建更新服务器文档里没说清楚，所以我也一直没弄

**Comment by sunzongzheng** [comment]
我自己的项目是把文件传到了国内的cdn，所以速度足够。我早期也是放到github release，确实是太慢了

ps:
1. 我没有找到免费签名的方案，可否分享一下？
2. 架梯子下载还很慢应该不会吧，我这边全局白名单翻墙，从github release下载东西一直很快

**Comment by hugetiny** [comment]
1.就是按照官方https://www.electron.build/code-signing 注册开发者账号，然后填一些全局变量。
我之前一直在10.13.6上开发的。不过注意一下10.14.5好像有变化：
https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/
2.应该是我这边移动网络问题

**Comment by hugetiny** [comment]
现在Mac不在身边，估计要按照electron.build里面的新方法才行了。

**Comment by sunzongzheng** [comment]
thx，我试试

**Comment by sunzongzheng** [comment]
签名确实免费，公证那一步暂时没成功，不过不影响自动更新。

自建更新服务器就是把打包后的所有文件(包括yml)全部放到文件服务的根目录。然后package.json里的配置指向文件服务地址就行，我已经测试通过
